### ISSUE TITLE
Led Glitch

### ISSUE THREAD

**Issue by Gaerisson** [not-matt/Systematic-LEDs#12]
Hey, I've got a problem with my LED, it's glitching with the new update, here is a video of what it does:

https://youtu.be/HBP3mC13J1U

I needed to add this 
**#define FASTLED_ESP8266_RAW_PIN_ORDER**
before 
**#include "FastLED.h"**

I still have somes errors when uploading the firmware:

In file included from C:\[LED]-Controler\arduino\ws2812_controller\ws2812_controller.ino:8:0:
F:\Users\gaetan\Documents\Arduino\libraries\FastLED-3.1.6/FastLED.h:17:21: note: #pragma message: FastLED version 3.001.006
     pragma message "FastLED version 3.001.006"
                     ^

In file included from F:\Users\gaetan\Documents\Arduino\libraries\FastLED-3.1.6/FastLED.h:68:0,
                 from C:\[LED]-Controler\arduino\ws2812_controller\ws2812_controller.ino:8:
F:\Users\gaetan\Documents\Arduino\libraries\FastLED-3.1.6/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
     pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^

I've got an **ESP8266** and a LED Strip of **300 LEDs** and my FPS is at 60, i've tried 90 but no change, help please :)

By the way, thanks for updating this awesome project 👍

**Comment by ahodges9** [comment]
Have you tried this fork for fast LED which adds DMA support (hopefully integrated into the mainline soon): https://github.com/coryking/FastLED

**Comment by Gaerisson** [comment]
Yes, thanks you fixed my problem :)
https://www.youtube.com/watch?v=0laTGXqIKF8

**Comment by ahodges9** [comment]
Great! We should update the README to start having our own instructions :)

**Comment by Gaerisson** [comment]
yes, thanks for response 😃
