### ISSUE TITLE
Cannot start main.py - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kennerblick** [not-matt/Systematic-LEDs#21]
I have pull the actual master and configured ip and the option no gui. When i start main.py:

" /opt/Systematic-LEDs/python/main.py
  File "/opt/Systematic-LEDs/python/main.py", line 1110
    for key, label, ui_element, *opts in visualizers[self.board].dynamic_effects_config[effect]:
                                ^
SyntaxError: invalid syntax
"

(the circumflex (^) is under the asterisk(*) bevor opts)

thank you for the effort

**Comment by gaijinsr** [comment]
You are probably using python 2.x, try python3.

**Comment by kennerblick** [comment]
Yes, thank you, that was the problem. Now comes the next one. I have Ubuntu Server, without GUI. In the config i have disabled GUI. when i start main.py:
 python3 /opt/Systematic-LEDs/python/main.py
Traceback (most recent call last):
  File "/opt/Systematic-LEDs/python/main.py", line 636, in <module>
    class GUI(QMainWindow):
NameError: name 'QMainWindow' is not defined

**Comment by charlieali** [comment]
what pyqt version are you using?

**Comment by kennerblick** [comment]
PyQt5 (5.10.1)
is installed.

**Comment by blassbasti** [comment]
@kennerblick did you figure out any solution for 'QMainWindow' is not defined??
