### ISSUE TITLE
Another startup problem

### ISSUE THREAD

**Issue by gaijinsr** [not-matt/Systematic-LEDs#22]
Hi, 
audio-reactive-led-strip-master works just fine for me, but when I try to start Systematic-LEDs, I get

~/LED/Systematic-LEDs-master/python$ python3 main.py 
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Traceback (most recent call last):
  File ".../LED/Systematic-LEDs-master/python/lib/microphone.py", line 21, in start_stream
    callback(y)
  File "main.py", line 1353, in microphone_update
    boards[board].show(outputs[board])
  File ".../LED/Systematic-LEDs-master/python/lib/devices.py", line 145, in show
    self._sock.sendto(message, (self._ip, self._port))
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1437, in <module>
    microphone.start_stream(microphone_update)
  File ".../LED/Systematic-LEDs-master/python/lib/microphone.py", line 27, in start_stream
    gui.label_error.setText('Audio buffer has overflowed {} times'.format(overflows))
NameError: name 'gui' is not defined

any idea what is happing here? I have no clue...

I am running Ubuntu 16.04 xenial, but I get the same problem with 18.04 bionic. Starting jackd does not help, either.

**Comment by ItsTheJetstream** [comment]
@gaijinsr What version of python are you running?

**Comment by gaijinsr** [comment]
I have python 3.5.2 and pyaudio 0.2.8.

**Comment by gaijinsr** [comment]
Yariv's observation that the invalid IP address in config.py is the culprit made me wish I had looked more closely at the error message. But the "socket.gaierror" really was buried in there rather deeply...
