### ISSUE TITLE
After 5-10 sec leds are out of sync and stop working

### ISSUE THREAD

**Issue by Yariv-h** [not-matt/Systematic-LEDs#29]
I flashed the esp8266 with upload speed of 57600, connected the data pin to D5 pin which is 4 pins left to the RX1 pin (worth to add this commend somewhere...) when starting the python application all the leds turned off and start getting signals from the python application.

using the following :
#define NUM_LEDS      100
#define DATA_PIN      5
//#define CLOCK_PIN   2
#define CHIPSET       WS2812B
#define COLOR_ORDER   GRB

The led stip itself is bigger the 100 leds but was tested it with only 100 leds. using WS2812B  led strip.

is there a way to get the output of the esp8266 device to see if there some errors?
@not-matt Can you please confirm that the setup it right?

**Comment by tarthim** [comment]
Aren't you supposed to connect to the RX1 pin instead of the D5 pin? I'm doing that, with basically your settings, and that's working smoothly.

**Comment by Yariv-h** [comment]
No, RX1 will not work, i had also the same problem. look at the board, you will see the following: 

![sku_441215_1](https://user-images.githubusercontent.com/3518124/38086382-c7caa7e2-335c-11e8-9e53-f603f04226b1.jpg)

ws2812_controller.ino you have the line of DATA_PIN      5  not sure how to change to to RX1 but you can change it to different data pin

Hope it will help, let me know please if the leds working well for you just to have in mind if i have wireing problem or its this version which make some issues.

thanks!

**Comment by not-matt** [comment]
Could you explain further what the problem is? A video of the lights
bugging out would be useful. Could you also run through why you are using
D5 over RX?

**Comment by Yariv-h** [comment]
i changed my power supply and its working just fine on D5 pin
