### ISSUE TITLE
Syntax errors in main.py

### ISSUE THREAD

**Issue by blassbasti** [not-matt/Systematic-LEDs#30]
I want to execute the main.py script to use the visualization but i get the following error:

`pi@raspberrypi:~/Systematic-LEDs/python $ sudo python main.py
  File "main.py", line 1110
    for key, label, ui_element, *opts in visualizers[self.board].dynamic_effects_config[effect]:
                                ^
SyntaxError: invalid syntax
`

what should i do about this?

**Comment by nhmann** [comment]
can you post line 1100 - 1120 of your main.py?

**Comment by blassbasti** [comment]
`                    config.settings["devices"][board]["effect_opts"][effect][key] = self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].currentText()
                return func
            def gen_checkbox_valuechanger(effect, key):
                def func():
                    config.settings["devices"][board]["effect_opts"][effect][key] = self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].isChecked()
                return func
            # Dynamically generate ui for settings
            if effect in visualizers[self.board].dynamic_effects_config:
                i = 0
                connecting_funcs[effect] = {}
                for key, label, ui_element, *opts in visualizers[self.board].dynamic_effects_config[effect]:
                    if opts: # neatest way  ^^^^^ i could think of to unpack and handle an unknown number of opts (if any) NOTE only works with py >=3.6
                        opts = list(opts[0])
                    if ui_element == "slider":
                        connecting_funcs[effect][key] = gen_slider_valuechanger(effect, key)
                        self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key] = QSlider(Qt.Horizontal)
                        self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].setMinimum(opts[0])
                        self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].setMaximum(opts[1])
                        self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].setValue(config.settings["devices"][board]["effect_opts"][effect][key])
                        self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].valueChanged.connect(
                                connecting_funcs[effect][key])`

thank you in advance for helping !

**Comment by blassbasti** [comment]
config.settings["devices"][board]["effect_opts"][effect][key] = self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].currentText()
                return func
            def gen_checkbox_valuechanger(effect, key):
                def func():
                    config.settings["devices"][board]["effect_opts"][effect][key] = self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].isChecked()
                return func
            # Dynamically generate ui for settings
            if effect in visualizers[self.board].dynamic_effects_config:
                i = 0
                connecting_funcs[effect] = {}
                for key, label, ui_element, *opts in visualizers[self.board].dynamic_effects_config[effect]:
                    if opts: # neatest way  ^^^^^ i could think of to unpack and handle an unknown number of opts (if any) NOTE only works with py >=3.6
                        opts = list(opts[0])
                    if ui_element == "slider":
                        connecting_funcs[effect][key] = gen_slider_valuechanger(effect, key)
                        self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key] = QSlider(Qt.Horizontal)
                        self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].setMinimum(opts[0])
                        self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].setMaximum(opts[1])
                        self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].setValue(config.settings["devices"][board]["effect_opts"][effect][key])
                        self.board_tabs_widgets[board]["grid_layout_widgets"][effect][key].valueChanged.connect(
                                connecting_funcs[effect][key])

ok i think you can read it better this way

**Comment by tarthim** [comment]
Your Pi is running Python2, where 3 is needed. Depending on the pi you can either run "python3" as it is already installed, or sudo apt-get install python3 (or google around how to get python3 for your OS)

**Comment by blassbasti** [comment]
I'm already using python3 now but I'm still running in a lot of problems

This is the latest: 
```
Traceback (most recent call last):
  File "main.py", line 636, in <module>
    class GUI(QMainWindow):
NameError: name 'QMainWindow' is not defined
```
 
I don't even want to use the gui and I'm not really sure what the problem is

**Comment by not-matt** [comment]
@blassbasti Fixed, my bad.
