### ISSUE TITLE
led strip flickering

### ISSUE THREAD

**Issue by luxxl** [not-matt/Systematic-LEDs#35]
Hello, 
I had similar issue before with my old strip and I tough that I managed to damage it so I bought new one and I have same issue as before with old one. In [Video](https://streamable.com/caslv) strip is flickering even on static gradient. I used NodeMcu lua V3 and wemos D1 mini but same flickering occurs, even tried different psu's any ideas? 
P.S. when i'm closing program flickering stops but when it's on even on static gradient strip flickers

**Comment by blassbasti** [comment]
it may be an electrical problem since you use a lot of pixels. how much current do you have?

**Comment by luxxl** [comment]
I'm currently using 20A PSU when I turn it on voltage drops 0.01v, didn't measured amperage but it should be enough to drive led's as it won't be all on white and i'm using like 50% brightness I tried ATX psu that have 40A on 5v buss still same. Yesterday I noticed that D1 mini board flicker a bit less than lua v3 and I'm starting to think that this have something to do with bad chip.

**Comment by ahodges9** [comment]
This looks a lot like the FastLED interrupt issues. Do you have FASTLED_ESP8266_DMA defined in your .ino and have you installed the proper fork? You can also try defining FASTLED_ALLOW_INTERRUPTS to 0 and see if that resolves your problem (see https://github.com/FastLED/FastLED/wiki/Interrupt-problems) if that does you likely don't have DMA working properly.

**Comment by luxxl** [comment]
Wow man thanks a lot. You just solved my problem now with interrupts 0 defined it works like a charm ;)

**Comment by ahodges9** [comment]
You really shouldn't use that because it essentially drops all interrupt (i.e. WiFi packets) while the LEDs are being written to. With reactive effects this is going to eventually bite you in the ass. Have you tried removing FastLED, installing this fork: https://github.com/coryking/FastLED, then just having FASTLED_ESP8266_DMA defined? This will use a slightly different approach to driving the LEDs that should be significantly better.

**Comment by luxxl** [comment]
it worked I tried reinstalling FastLED before but not this particularly fork it works as intended now. Thanks for help :)

**Comment by blassbasti** [comment]
I think I have a very similar FastLED issue as you can see in this [youtube video](https://youtu.be/yEi8nfOV8V4).

I removed all FastLED libraries from my laptop and reinstalled the suggested one. 
Another thing that is unclear to me is if i the .ino file for the ESP should say `#include "FastLED.h"` or `#include <FastLED.h>` and what the difference between those notations is.
