### ISSUE TITLE
Fresh clone error

### ISSUE THREAD

**Issue by Yariv-h** [not-matt/Systematic-LEDs#38]
(RGB) bash-3.2$ python main.py 
  File "main.py", line 80
    merged_general_config = {**config.default_general_config, **gen_config}
                              ^
SyntaxError: invalid syntax

(Using MAC)

**Comment by Moonbase59** [comment]
You might need Python 3.6.5+ to make this software work. I had exactly the same error (on Linux) when using older Python3 versions.
