### ISSUE TITLE
No user colours found, No user gradients found

### ISSUE THREAD

**Issue by plabonhasan** [not-matt/Systematic-LEDs#39]
Hi Mat, long, long time i try this project then  your Tutorial very help full and detail thanks. i am try your project all good to end but  some error message C:\Systematic-LEDs-master\python>python main.py {Enter}
error message.............................  

No user colours found
No user gradients found)  

Again thank You so much,

**Comment by not-matt** [comment]
Hey, that's not an error, just a debug thing I forgot to remove. Don't worry about it!
