### ISSUE TITLE
Can't put Esp8266 into LED Strip Manager

### ISSUE THREAD

**Issue by CreamySoda** [not-matt/Systematic-LEDs#44]
After putting in all the required information, including the MAC address, the Add Device button is still greyed out. I have verified multiple times that that was the right MAC address, and it is the only input that was red, the rest were green. Any help is appreciated

**Comment by Aurumalpha** [comment]
I have the same problem, please help us

**Comment by blassbasti** [comment]
i recently downloaded the latest release of the project and everything worked fine with connecting devices.

I didn't use the auto-detect feature with the MAC-address though. for the MAC-address I used "aa-bb-cc-dd-ee-ff" and the rest of the parameteres like IP, Port etc I entered valid values.

**Comment by not-matt** [comment]
Fixed :)
