### ISSUE TITLE
Error invalid syntax

### ISSUE THREAD

**Issue by 94maldini** [not-matt/Systematic-LEDs#52]
File "E:/Aplikasi/Apps/esp8266/Systematic-LEDs-master/Systematic-LEDs-master/python/main.py", line 85
    merged_general_config = {**config.default_general_config, **gen_config}
                              ^
SyntaxError: invalid syntax

kenapa bisa terjadi ?

**Comment by 94maldini** [comment]
my Python 3.6

**Comment by ThunderMerweS** [comment]
Good day,

I have been stuck on this exact same error for a couple of hours now. 

I have tried all versions of Python, from 3.6 and up, and makes no difference, unfortunately.

Any other Ideas?

**Comment by Andriejus** [comment]
when I had similar problem, so I edited config.py as needed and it worked for me.
https://github.com/not-matt/Systematic-LEDs/issues/62
