### ISSUE TITLE
ESP8266 Wont accept code?

### ISSUE THREAD

**Issue by SgtBlade** [not-matt/Systematic-LEDs#54]
I keep getting some weird logs in my console. Can anyone tell me what it is? The output I'm getting at 74880 Baut is:

⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮
18:15:43.754 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
18:15:43.754 -> 
18:15:43.754 -> load 0x4010f000, len 1384, room 16 
18:15:43.754 -> tail 8
18:15:43.754 -> chksum 0x2d
csum 0x2d
18:15:43.787 -> vbb28d4a3
18:15:43.787 -> ~ld
⸮⸮⸮⸮⸮⸮Vi+U(⸮⸮J⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮

I am also getting some weird things when uploading to my module, there I'm getting this: 

sketch\fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

Sketch uses 282480 bytes (27%) of program storage space. Maximum is 1044464 bytes.
Global variables use 30216 bytes (36%) of dynamic memory, leaving 51704 bytes for local variables. Maximum is 81920 bytes.
Uploading 286624 bytes from C:\Users\myname\AppData\Local\Temp\arduino_build_844614/ws2812_controller.ino.bin to flash at 0x00000000
................................................................................ [ 28% ]
................................................................................ [ 57% ]
................................................................................ [ 85% ]
........................................                                         [ 100% ]

**Comment by richyxi** [comment]
does it work?

**Comment by SgtBlade** [comment]
> does it work?

Nope but I did fix it, I uploaded blank stuff to it and then uploaded a redownloaded file which worked
