### ISSUE TITLE
Leds freeze

### ISSUE THREAD

**Issue by SgtBlade** [not-matt/Systematic-LEDs#55]
On some modes my leds are freezing, I'm not sure what's causing it but I suspect it is something in the packed sent to the ESP8266 that causes it to crash or freeze up, when I try pinging the ESP after it had happened it says request timed out. 
Anyone knows if this is an configuration issue or a coding issue?

**Comment by SgtBlade** [comment]
Update, I think it has something to do with if the color led reaches it max

**Comment by gaijinsr** [comment]
This sounds very much like your power supply is not up to the job. Try with just a few LEDs (no need to change the number of LEDs in the config), if that is stable, replace your PSU.

**Comment by SgtBlade** [comment]
Hi, thanks for the reply. The powersupply was indeed not supplying enough amps but that seems not to be the issue. I've currently connected my setup with a bench powersupply and the issue still seems to be there.

**Comment by SgtBlade** [comment]
Update: I fixed the issue, not sure what did it but for anyone in the future having this, these are the things I did: (using 180 leds & ESP8266)
Change psu to one with a max 2.5 Amps (highest i've gotten so far is 2 so that leaves 0.5 just in case)
Assigned new IP to the esp
Changed the sensor name and ota password
Removed and re-added my device in the Visualization python script
