### ISSUE TITLE
Glitch on a single pixel

### ISSUE THREAD

**Issue by kanapoutz78** [not-matt/Systematic-LEDs#6]
Hi !

First of all, I would like to thank you for your hard work : this project is amazing 👍 

I have a strange issue with this new version. I have a set-up with esp and a strip of 150 pixels. One of them (the 50th) has an issue with the red color. However, I put the right number of pixels in the arduino and python code....

I first thought it was my LED strip but it is not since I can set all pixels red with a previous version of the code...

I don't have so many clues about the problem. I tried to modify the number of pixels : put 151 or 149 instead of 150 but it just changed the index of the pixel which has the problem and the color affected (blue / red).

Here are some pics about this :

![img_20180303_005206](https://user-images.githubusercontent.com/25565600/36927526-69033118-1e7e-11e8-8f39-a8c177f5d4e1.jpg)

![img_20180303_005156](https://user-images.githubusercontent.com/25565600/36927535-7c28aca0-1e7e-11e8-8b04-b23564fc7039.jpg)

![img_20180303_010023](https://user-images.githubusercontent.com/25565600/36927550-9771053e-1e7e-11e8-9c1c-b24307c318f4.jpg)

And a video showing the issue :)  : 
https://drive.google.com/file/d/18rCin0ziWvUkuNiqIwcvCkuaSHGt52iV/view?usp=sharing

**Comment by not-matt** [comment]
I have a similar problem on both my other strips. I thought it was a dead pixel. However, yours in the exact same spot too. 

For me, the dead pixel won't show green, but red and blue work fine. Looks like yours won't show red. How is it for blue? I can't tell by the pictures.

**Comment by kanapoutz78** [comment]
If I set the number of pixels  correctly (150), the pixel affected can't light up red but still be blue or red (you can show it in the video). But if I changed the number, an other pixel is affected and the color missing is green or blue (in case of 149 or 151).

I don't know if it is a problem of the esp firmware or if it is in the python code...

**Comment by not-matt** [comment]
So here's something else - You have 150 pixels, the error is on the 50th. That's exactly 1/3rd the way, the same as on my two strips.

**Comment by kanapoutz78** [comment]
An other clue would be to know if the code works on an other device without this problem...

**Comment by kanapoutz78** [comment]
Solved with the new firmware for esp8266. You can close this issue 😊

**Comment by not-matt** [comment]
Ah sweet, forgot about that!

Cheers

**Comment by ahodges9** [comment]
Another benefit of FastLED :)
