### ISSUE TITLE
How tu run main.py on iMac + Anaconda?

### ISSUE THREAD

**Issue by Andriejus** [not-matt/Systematic-LEDs#62]
Hello Sirs!

Could you please tell me what command to type or how to run file main.py??
I have installed Anaconda and these: "conda install numpy scipy pyqtgraph
pip install pyaudio". So next step would be to run main.py. But how to do it?:)

P.S. Im using MacOS

Thanks in advance!

**Comment by Yariv-h** [comment]
python main.py

**Comment by Andriejus** [comment]
im gettin this: 
bash-3.2$ python main.py
python: can't open file 'main.py': [Errno 2] No such file or directory
bash-3.2$

**Comment by Yariv-h** [comment]
did you go into the directory of the project? try to create hello world py file and run it within anaconda to make sure it ok..

**Comment by Andriejus** [comment]
How to go into directory of the project? What command to type?

**Comment by Yariv-h** [comment]
did you get the terminal window opened? 
cd <folder name>

**Comment by Andriejus** [comment]
Yes, I opened terminal and here is what I get:
bash-3.2$ cd ~/Downloads/Systematic-LEDs-master/python python main.py
bash-3.2$ python main.py
  File "main.py", line 93
    merged_general_config = {**config.default_general_config, **gen_config}
                              ^
SyntaxError: invalid syntax
bash-3.2$

**Comment by Andriejus** [comment]
Which versions of Anaconda and python are you using? Maybe its because of versions.. so I could install versions like yours and try..

**Comment by Andriejus** [comment]
You can look here: https://github.com/not-matt/Systematic-LEDs/issues/66

**Comment by Yariv-h** [comment]
10X!
