### ISSUE TITLE
How to find MAC adrress of esp8266?

### ISSUE THREAD

**Issue by Andriejus** [not-matt/Systematic-LEDs#63]
Ho to find MAC adress of ESP8266? So I could enter it to LED strip manager? 
Or maybe I dont need it? Maybe I should disable autodetecting(but I dont know how to do it..)?

Also should I connect LED strip do RX pin on esp8266? in webcontroller.ino it says LED_PIN is 7.

**Comment by Andriejus** [comment]
I disabled MAC adress in config.py file and connected LED pin to RX on nodemcu. Working.

**Comment by richyxi** [comment]
how did u disable  MAC adress in config?

**Comment by Andriejus** [comment]
I disabled "Autodetect", by making it "False" in config.py file.
