### ISSUE TITLE
LED strip manager hangs on.. (not responding) macOS+Anaconda

### ISSUE THREAD

**Issue by Andriejus** [not-matt/Systematic-LEDs#66]
When I run main.py - LED strip manager window pops up and hangs on.(python is not responding). its only active for 4 seconds and then wheel is just spinnng and I can not do anything:( Trying to find what is causing that. Im using Anaconda+python 3.6.5. on macOS High Sierra.

P.S. I used the same files on Windows 7 and everything was working fine.

![screen shot 2019-01-29 at 11 54 54 pm](https://user-images.githubusercontent.com/38490002/51946376-8c6d3a00-2421-11e9-8f96-58a5fe7fb161.png)

_Originally posted by @Andriejus in https://github.com/not-matt/Systematic-LEDs/issues/62#issuecomment-457965946_

**Comment by Andriejus** [comment]
WOW! it worked! Thank you SO MUCH! Now I can move on. It works with Anaconda+python 3,6,5. Also I tried to run it only with python, but I got some erros.. Wondering what is the quickiest way to launch main.py. Because it takes quite long to open anaconda and then type in commands:)

**Comment by lpearl** [comment]
@Andriejus Glad, it works! just remember to close this issue. I don't use Anaconda to run it on my mac just straight through python. The quickest way to start it up would be by making a .command file that launches main.py. I have anaconda installed on another computer so I can write the script when I get back.
