### ISSUE TITLE
 Audio setup on MAC (crashes)?

### ISSUE THREAD

**Issue by Andriejus** [not-matt/Systematic-LEDs#68]
Hello,

could someone explain how to setup audio on MAC? It works with microphone. But I dont know how to setup  built-in input..:( I want my LEDS to react to music from my computer. If I try to use other input (picture attached) so it crashes and I get this error:

File "main.py", line 1263, in set_mic
    microphone.setDevice(mic_button_group.checkedId())
  File "main.py", line 858, in setDevice
    self.device_id = self.devices[device_id]["index"]
IndexError: list index out of range
Abort trap: 6

![screen shot 2019-02-01 at 11 13 01 pm](https://user-images.githubusercontent.com/38490002/52153077-eddb1600-2678-11e9-95c5-526451ef5108.png)

P.S. and I dont want to use Loopback, because its not free:)

**Comment by GabeDahl** [comment]
Look into something called Soundflower. 

You can use this along with the Audio MIDI setup to loop your audio output back into the computer as an input.

**Comment by Andriejus** [comment]
Thank you. I used soundflower and now it works!:)
