### ISSUE TITLE
Python error using pyaudio

### ISSUE THREAD

**Issue by richyxi** [not-matt/Systematic-LEDs#69]
I got this error errno -9996] invalid input device (no default output device) somebody has any clue

**Comment by Maerchensarg** [comment]
Can confirm this. GUI pops up for a seconds and quits:

(RGB) C:\Users\STFU\Desktop\Systematic-LEDs-master\Systematic-LEDs-master\python>python main.py
Could not find settings.ini
No user colours found
No user gradients found
Traceback (most recent call last):
  File "main.py", line 2046, in <module>
    microphone = Microphone(microphone_update)
  File "main.py", line 842, in __init__
    device_info = py_audio.get_device_info_by_host_api_device_index(0,i)
  File "C:\Users\STFU\Anaconda2\envs\RGB\lib\site-packages\pyaudio.py", line 852, in get_device_info_by_host_api_device_index
    host_api_device_index)
OSError: [Errno -9996] Invalid device

**Comment by Maerchensarg** [comment]
Thank you. It works with Anaconda 3. Sorry for the inconvenience.

**Comment by richyxi** [comment]
Don't worry bro
