### ISSUE TITLE
Frequency slider crash

### ISSUE THREAD

**Issue by kanapoutz78** [not-matt/Systematic-LEDs#9]
If I try to change the frequency range with the slider it crashes and the error is : 

Traceback (most recent call last):
  File "D:\Projets\guirelande\Systematic-LEDs-master\python\main.py", line 1026, in set_freq_max
    dsp.create_mel_bank()
AttributeError: module 'lib.dsp' has no attribute 'create_mel_bank'

I think it should be DSP and not dsp and maybe put the self attribute when calling the method as it follows. The cursor works without crashing but changing the max frequency value has no effects so maybe my correction is wrong....

`DSP.create_mel_bank(self)
        def set_freq_min():
            config.settings["configuration"]["MIN_FREQUENCY"] = self.board_tabs_widgets[board]["freq_slider"].start()
            DSP.create_mel_bank(self)
        def set_freq_max():
            config.settings["configuration"]["MAX_FREQUENCY"] = self.board_tabs_widgets[board]["freq_slider"].end()
            DSP.create_mel_bank(self)`

**Comment by not-matt** [comment]
Fixed, but frequency slider found to no longer work too.

**Comment by not-matt** [comment]
Fixed that too.
